version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: ./deploy/Dockerfile
    image: ticket:${TICKET_VERSION:-latest}
    restart: always
    env_file:
    - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      TICKET_HOST: 0.0.0.0
      TICKET_DB_HOST: ticket-db
      TICKET_DB_PORT: 5432
      TICKET_DB_USER: ticket
      TICKET_DB_PASS: ticket
      TICKET_DB_BASE: ticket

  db:
    image: postgres:13.8-bullseye
    hostname: ticket-db
    environment:
      POSTGRES_PASSWORD: "ticket"
      POSTGRES_USER: "ticket"
      POSTGRES_DB: "ticket"
    volumes:
    - ticket-db-data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: pg_isready -U ticket
      interval: 2s
      timeout: 3s
      retries: 40

  migrator:
    image: ticket:${TICKET_VERSION:-latest}
    restart: "no"
    command: aerich upgrade
    environment:
      TICKET_DB_HOST: ticket-db
      TICKET_DB_PORT: 5432
      TICKET_DB_USER: ticket
      TICKET_DB_PASS: ticket
      TICKET_DB_BASE: ticket
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: bitnami/redis:6.2.5
    hostname: "ticket-redis"
    restart: always
    environment:
      ALLOW_EMPTY_PASSWORD: "yes"
    healthcheck:
      test: redis-cli ping
      interval: 1s
      timeout: 3s
      retries: 50



volumes:
  ticket-db-data:
    name: ticket-db-data
